---
title: "AIC"
author: "Ying Jin"
date: "2/18/2021"
output: html_document
---

```{r setup, include=FALSE}
library(tidyverse)

set.seed(1234)

source("Generator2.R")
```


```{r}
# define number of diff signals
n_s.1 = 3
n_s.2 = c(2,2,2)
p = 250 # total parameter size
n_s.3 = sum(n_s.2)
n = 200 #sample size
n_exp = 1 # iteration times


# get a vector of strong, wbc and weak signal
vec_s.1 = c()
for (i in 1:n_s.1){
  vec_s.1 = rbind(vec_s.1,paste("x",i,sep = ""))
}
vec_s.1 = c(vec_s.1)

vec_s.2 = c()
for (i in n_s.1+1:sum(n_s.2)){
  vec_s.2 = rbind(vec_s.2,paste("x",i,sep = ""))
}
vec_s.2 = c(vec_s.2)

vec_s.3 = c()
for (i in n_s.1+sum(n_s.2)+1:n_s.3){
  vec_s.3 = rbind(vec_s.3,paste("x",i,sep = ""))
}
vec_s.3 = c(vec_s.3)

# get the threshold

thre = sqrt(log(p)/n)
c = 1
b = .3
# get beta 
beta = rep(c(runif(n_s.1,c*thre,c*thre+b),runif(sum(n_s.2)+n_s.3,-c*thre,c*thre),0,1),
           times = c(rep(1,n_s.1),rep(1,sum(n_s.2)+n_s.3),p-n_s.1-sum(n_s.2)-n_s.3,1))

# col names
col_name = c()
for (i in 1:p){
  col_name = rbind(col_name,paste0("x",i))
}
col_name = rbind(col_name,"y")
```



```{r}
# AIC selection procedure

prop_t = prop_f = prop_stro = numeric(n_exp)

for (i in 1:n_exp)
{
  data = Gen_Method2(n_s.1,n_s.2,n_s.3,P=p,N=n)
  
# get y 
y =  data %*% as.matrix(beta)

# generate dataset for regression 
df = 
  as_tibble(data[,-(p+1)]) %>% 
  mutate(y = y) %>% 
  setNames(col_name) 
  
  fit.forward = step(object = lm(y ~ 1, data = df),
                      scope = formula(lm(y ~ ., data = df)), 
                      direction = "forward", k = 2, trace = 0) 
  
 selected <- attr(x = fit.forward$terms, which = "variables")
 
 n_s.1_selected = sum(as.character(selected) %in% vec_s.1)
 n_s.2_selected = sum(as.character(selected) %in% vec_s.2)
 n_s.3_selected = sum(as.character(selected) %in% vec_s.3)
 prop_t[[i]] = (n_s.1_selected+sum(n_s.2)-n_s.2_selected+n_s.3- n_s.3_selected)/(n_s.1+sum(n_s.2)+n_s.3)
 
 prop_f[[i]] = (n_s.1 - n_s.1_selected + n_s.2_selected +n_s.3_selected)/(n_s.1+sum(n_s.2)+n_s.3)
 
 prop_stro[[i]] = n_s.1_selected/n_s.1
}

avg_prop_t = mean(prop_t)
avg_prop_t

avg_prop_f = mean(prop_f)
avg_prop_f

avg_prop_stro = mean(prop_stro)
avg_prop_stro
```

