---
title: "Lasso"
author: "Jiying Han"
date: "2/18/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(corrplot)
library(glmnet)
set.seed(1234)

source("Generator2.R")
```




```{r}
# define number of diff signals
n_s.1 = 3
n_s.2 = c(2,2,2)
n_s.3 = sum(n_s.2)
p = 120 # total parameter size
n = 100 #sample size
n_exp = 5 # itertation times


# get a vector of strong signal
vec_s.1 = c()
for (i in 1:n_s.1){
  vec_s.1 = rbind(vec_s.1,paste("x",i,sep = ""))
}
vec_s.1 = c(vec_s.1)

# get the threshold

thre = sqrt(log(p)/n)

# get y 

beta = rep(c(30,0.1,0,1),c(n_s.1,12,p-n_s.1-12,1))


# col names
col_name = c()
for (i in 1:p){
  col_name = rbind(col_name,paste0("x",i))
}
col_name = rbind(col_name,"y")
```



```{r}
prop_s.1_selected = numeric(n_exp)

for (i in 1:n_exp)
{
  data = Gen_Method1(n_s.1,c(2,2,2),6,p,n) 
  
# get y 
y =  data %*% as.matrix(beta)

# generate dataset for regression 
df = 
 as_tibble(data[,-(p+1)]) %>% 
 mutate(y = y) %>% 
 setNames(col_name) 

 
# generate in matrix format
df_mat = model.matrix(y~ .,df)
df_mat1 = model.matrix(y~ .,df)[, -1]

# explore the range of lambda
# cv.ridge <- cv.glmnet(df_mat1, y, alpha = 1, nlambda = 200)
# plot(cv.ridge)
#abline(h = (cv.ridge$cvm + cv.ridge$cvsd)[which.min(cv.ridge$cvm)], col = 4, lwd = 2)

# lasso slelction process
set.seed(2)
fit.lasso <- cv.glmnet(y = y, x = df_mat1, 
                       alpha = 1,    
                       lambda = exp(seq(1, -3, length = 100)), 
                       type.measure = "mse") 

# extract coefficient
 coeff = predict(fit.lasso, s = "lambda.min", type = "coefficients")[-1,] %>% as.tibble() 
   attr(x = fit.forward$terms, which = "variables")
 

 

# forward  
  fit.forward = step(object = lm(y ~ 1, data = df),
                      scope = formula(lm(y ~ ., data = df)), 
                      direction = "forward", k = 2, trace = 0)
  


 
 selected <- attr(x = fit.forward$terms, which = "variables")
 
 n_s.1_selected = sum(as.character(selected) %in% vec_s.1)
 prop_s.1_selected[[i]] = n_s.1_selected/n_s.1
}
```

