---
title: "Lasso"
author: "Jiying Han"
date: "2/18/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(corrplot)
library(glmnet)
set.seed(1234)

source("Generator2.R")
```




```{r}
# define number of diff signals
n_s.1 = 3
n_s.2 = c(2,2,2)
n_s.3 = sum(n_s.2)
p = 250 # total parameter size
n = 200 # sample size
n_exp = 1 # iteration times


# get a vector of strong signal
vec_s.1 = c()
for (i in 1:n_s.1){
  vec_s.1 = rbind(vec_s.1,paste("x",i,sep = ""))
}
vec_s.1 = c(vec_s.1)

# get a vector of weak signal（correlated and independent）
vec_s.2 = c()
for (i in n_s.1+1:sum(n_s.2)){
  vec_s.2 = rbind(vec_s.2,paste("x",i,sep = ""))
}
vec_s.2 = c(vec_s.2)

vec_s.3 = c()
for (i in n_s.1+sum(n_s.2)+1:n_s.3){
  vec_s.3 = rbind(vec_s.3,paste("x",i,sep = ""))
}
vec_s.3 = c(vec_s.3)


# get the threshold

thre = sqrt(log(p)/n)
c = 1
b = .3

# get beta

# beta = rep(c(30,0.1,0,1),c(n_s.1,12,p-n_s.1-12,1))

beta = rep(c(runif(n_s.1,c*thre,c*thre+b),runif(sum(n_s.2)+n_s.3,-c*thre,c*thre),0,1),
           times = c(rep(1,n_s.1),rep(1,sum(n_s.2)+n_s.3),p-n_s.1-sum(n_s.2)-n_s.3,1))

# col names
col_name = c()
for (i in 1:p){
  col_name = rbind(col_name,paste0("x",i))
}
col_name = rbind(col_name,"y")
```



```{r}
prop_lasso_t = prop_lasso_f = prop_lasso_stro = numeric(n_exp)

for (i in 1:n_exp)
{
  data = Gen_Method1(n_s.1,n_s.2,n_s.3,P=p,N=n) 
  
# get y 
y =  data %*% as.matrix(beta)

# generate dataset for regression 
df = 
 as_tibble(data[,-(p+1)]) %>% 
 mutate(y = y) %>% 
 setNames(col_name) 

 
# generate in matrix format
df_mat = model.matrix(y~ .,df)
df_mat1 = model.matrix(y~ .,df)[, -1]

# explore the range of lambda
set.seed(1234)
cv.lasso <- cv.glmnet(df_mat1, y, alpha = 1, nlambda = 200)
cv.lasso$lambda.min






#plot(cv.lasso)
#abline(h = (cv.lasso$cvm + #cv.lasso$cvsd)[which.min(cv.lasso$cvm)], col = 4, lwd = 2)

# lasso selection process
set.seed(1234)
fit.lasso <- cv.glmnet(y = y, x = df_mat1, 
                       alpha = 1,    
                       lambda = exp(seq(1, -3, length = 100)), 
                       type.measure = "mse") 

# extract coefficient
 coeff = predict(fit.lasso, 
                 s = "lambda.min", 
                 type = "coefficients")[-1,] %>% 
         as.tibble() %>% 
         mutate(number = 1:p) %>% 
         filter(value != 0) 
 ceoff_s.1 = paste(c('x'),coeff$number,  sep = '')

 
 n_s.1_lasso_selected = sum(as.character(ceoff_s.1) %in% vec_s.1)
 n_s.2_lasso_selected = sum(as.character(ceoff_s.1) %in% vec_s.2)
 n_s.3_lasso_selected = sum(as.character(ceoff_s.1) %in% vec_s.3)
 
 prop_lasso_t[[i]] = (n_s.1_lasso_selected+n_s.2_lasso_selected+ n_s.3_lasso_selected)/(n_s.1+sum(n_s.2)+n_s.3)
 
 prop_lasso_f[[i]] = (sum(1-as.character(ceoff_s.1) %in%c(as.character(vec_s.1),as.character(vec_s.2),as.character(vec_s.3))))/(p-n_s.1-sum(n_s.2)-n_s.3)

 prop_lasso_stro[[i]] = n_s.1_lasso_selected/n_s.1
}


avg_prop_lasso_t = mean(prop_lasso_t)
avg_prop_lasso_t

avg_prop_lasso_f = mean(prop_lasso_f)
avg_prop_lasso_f

avg_prop_lasso_stro = mean(prop_lasso_stro)
avg_prop_lasso_stro 

```



